import { createHash, randomUUID, timingSafeEqual } from 'node:crypto';

export type Role = 'client' | 'professional' | 'admin';
export type CertificationType = 'CA' | 'CMA' | 'CFA' | 'CPA' | 'MBA' | 'CS';
export type JobStatus = 'open' | 'contracted' | 'closed';
export type ProposalStatus = 'submitted' | 'accepted' | 'rejected';
export type VerificationStatus = 'unsubmitted' | 'pending' | 'approved' | 'rejected';
export type MilestoneStatus = 'draft' | 'funded' | 'released' | 'disputed' | 'refunded';

export interface User { id: string; email: string; passwordHash: string; roles: Role[]; emailVerified: boolean; suspended: boolean; createdAt: Date; }
export interface ProfessionalProfile { userId: string; name: string; headline: string; bio: string; certifications: Certification[]; yearsExperience: number; specializations: string[]; hourlyRate: number; languages: string[]; verificationStatus: VerificationStatus; rating: number; reviewCount: number; }
export interface Certification { type: CertificationType; licenseNumber: string; documentKey: string; }
export interface ServiceListing { id: string; professionalId: string; title: string; description: string; category: string; tags: string[]; fixedPrice: number; active: boolean; }
export interface JobPosting { id: string; clientId: string; title: string; description: string; category: string; tags: string[]; budget: number; deadline: Date; requiredCertification?: CertificationType; status: JobStatus; }
export interface Proposal { id: string; jobId: string; professionalId: string; price: number; timelineDays: number; coverNote: string; status: ProposalStatus; }
export interface Contract { id: string; jobId: string; clientId: string; professionalId: string; proposalId: string; milestones: Milestone[]; status: 'active' | 'completed' | 'disputed' | 'cancelled'; }
export interface Milestone { id: string; title: string; amount: number; platformFee: number; status: MilestoneStatus; paymentIntentId?: string; }
export interface Review { id: string; contractId: string; reviewerId: string; revieweeId: string; rating: number; comment: string; flagged: boolean; }
export interface Notification { id: string; userId: string; topic: string; body: string; read: boolean; createdAt: Date; }

export class MarketplaceError extends Error { constructor(public code: string, message: string) { super(message); } }

const isEmail = (value: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const assertNonEmpty = (value: string, field: string) => { if (!value.trim()) throw new MarketplaceError('VALIDATION_ERROR', `${field} is required`); };
const assertPositive = (value: number, field: string) => { if (!Number.isFinite(value) || value <= 0) throw new MarketplaceError('VALIDATION_ERROR', `${field} must be positive`); };
const hashPassword = (password: string, salt = randomUUID()) => `${salt}:${createHash('sha256').update(`${salt}:${password}`).digest('hex')}`;
const verifyPassword = (password: string, stored: string) => { const [salt] = stored.split(':'); if (!salt) return false; const candidate = hashPassword(password, salt); return timingSafeEqual(Buffer.from(candidate), Buffer.from(stored)); };

export interface PaymentGateway { createHold(amount: number, contractId: string, milestoneId: string): Promise<string>; releaseHold(paymentIntentId: string, amount: number): Promise<void>; refundHold(paymentIntentId: string, amount: number): Promise<void>; }

export class InMemoryPaymentGateway implements PaymentGateway {
  public holds = new Map<string, { amount: number; state: 'held' | 'released' | 'refunded' }>();
  async createHold(amount: number): Promise<string> { assertPositive(amount, 'amount'); const id = `pi_${randomUUID()}`; this.holds.set(id, { amount, state: 'held' }); return id; }
  async releaseHold(paymentIntentId: string, amount: number): Promise<void> { const hold = this.holds.get(paymentIntentId); if (!hold || hold.state !== 'held' || hold.amount !== amount) throw new MarketplaceError('PAYMENT_RELEASE_FAILED', 'Payment hold cannot be released'); hold.state = 'released'; }
  async refundHold(paymentIntentId: string, amount: number): Promise<void> { const hold = this.holds.get(paymentIntentId); if (!hold || hold.state !== 'held' || hold.amount !== amount) throw new MarketplaceError('PAYMENT_REFUND_FAILED', 'Payment hold cannot be refunded'); hold.state = 'refunded'; }
}

export class Marketplace {
  users = new Map<string, User>(); profiles = new Map<string, ProfessionalProfile>(); listings = new Map<string, ServiceListing>(); jobs = new Map<string, JobPosting>(); proposals = new Map<string, Proposal>(); contracts = new Map<string, Contract>(); reviews: Review[] = []; notifications: Notification[] = []; private acceptedJobs = new Set<string>();
  constructor(private payments: PaymentGateway, private platformFeeRate = 0.1) {}

  register(email: string, password: string, role: Exclude<Role, 'admin'>): User { if (!isEmail(email)) throw new MarketplaceError('INVALID_EMAIL', 'A valid email is required'); if (password.length < 12) throw new MarketplaceError('WEAK_PASSWORD', 'Password must be at least 12 characters'); if ([...this.users.values()].some(u => u.email === email.toLowerCase())) throw new MarketplaceError('DUPLICATE_SIGNUP', 'Email is already registered'); const user: User = { id: randomUUID(), email: email.toLowerCase(), passwordHash: hashPassword(password), roles: [role], emailVerified: false, suspended: false, createdAt: new Date() }; this.users.set(user.id, user); return user; }
  authenticate(email: string, password: string): User { const user = [...this.users.values()].find(u => u.email === email.toLowerCase()); if (!user || !verifyPassword(password, user.passwordHash)) throw new MarketplaceError('INVALID_CREDENTIALS', 'Invalid credentials'); if (user.suspended) throw new MarketplaceError('SUSPENDED', 'Account is suspended'); return user; }
  verifyEmail(userId: string): void { this.requireUser(userId).emailVerified = true; }
  createAdmin(email: string): User { const user: User = { id: randomUUID(), email, passwordHash: hashPassword(randomUUID()), roles: ['admin'], emailVerified: true, suspended: false, createdAt: new Date() }; this.users.set(user.id, user); return user; }

  upsertProfessionalProfile(userId: string, input: Omit<ProfessionalProfile, 'userId' | 'verificationStatus' | 'rating' | 'reviewCount'>): ProfessionalProfile { const user = this.requireRole(userId, 'professional'); if (!user.emailVerified) throw new MarketplaceError('EMAIL_UNVERIFIED', 'Email must be verified before onboarding'); input.certifications.forEach(c => { assertNonEmpty(c.licenseNumber, 'licenseNumber'); assertNonEmpty(c.documentKey, 'documentKey'); }); const profile = { ...input, userId, verificationStatus: 'pending' as const, rating: 0, reviewCount: 0 }; this.profiles.set(userId, profile); this.notify(userId, 'verification.pending', 'Your credentials were submitted for admin review.'); return profile; }
  reviewVerification(adminId: string, professionalId: string, approved: boolean, reason = ''): void { this.requireRole(adminId, 'admin'); const profile = this.requireProfile(professionalId); profile.verificationStatus = approved ? 'approved' : 'rejected'; this.notify(professionalId, approved ? 'verification.approved' : 'verification.rejected', approved ? 'Your profile is verified.' : `Verification rejected: ${reason}`); }

  createListing(professionalId: string, input: Omit<ServiceListing, 'id' | 'professionalId' | 'active'>): ServiceListing { const profile = this.requireProfile(professionalId); if (profile.verificationStatus !== 'approved') throw new MarketplaceError('UNVERIFIED_PROFESSIONAL', 'Only verified professionals can publish listings'); assertPositive(input.fixedPrice, 'fixedPrice'); const listing = { ...input, id: randomUUID(), professionalId, active: true }; this.listings.set(listing.id, listing); return listing; }
  postJob(clientId: string, input: Omit<JobPosting, 'id' | 'clientId' | 'status'>): JobPosting { this.requireRole(clientId, 'client'); assertPositive(input.budget, 'budget'); if (input.deadline <= new Date()) throw new MarketplaceError('INVALID_DEADLINE', 'Deadline must be in the future'); const job = { ...input, id: randomUUID(), clientId, status: 'open' as const }; this.jobs.set(job.id, job); return job; }
  searchListings(query: string, filters: Partial<{ certification: CertificationType; maxPrice: number; language: string }>): ServiceListing[] { const q = query.toLowerCase(); return [...this.listings.values()].filter(l => l.active && (!q || `${l.title} ${l.description} ${l.tags.join(' ')}`.toLowerCase().includes(q)) && (!filters.maxPrice || l.fixedPrice <= filters.maxPrice) && (!filters.language || this.requireProfile(l.professionalId).languages.includes(filters.language)) && (!filters.certification || this.requireProfile(l.professionalId).certifications.some(c => c.type === filters.certification))); }

  submitProposal(professionalId: string, jobId: string, input: Omit<Proposal, 'id' | 'jobId' | 'professionalId' | 'status'>): Proposal { const profile = this.requireProfile(professionalId); const job = this.requireJob(jobId); if (profile.verificationStatus !== 'approved') throw new MarketplaceError('UNVERIFIED_PROFESSIONAL', 'Only verified professionals can bid'); if (job.status !== 'open') throw new MarketplaceError('JOB_CLOSED', 'Job is not open'); if (job.requiredCertification && !profile.certifications.some(c => c.type === job.requiredCertification)) throw new MarketplaceError('CERTIFICATION_REQUIRED', 'Professional lacks required certification'); assertPositive(input.price, 'price'); const proposal = { ...input, id: randomUUID(), jobId, professionalId, status: 'submitted' as const }; this.proposals.set(proposal.id, proposal); this.notify(job.clientId, 'proposal.new', `New proposal for ${job.title}`); return proposal; }
  acceptProposal(clientId: string, proposalId: string): Contract { const proposal = this.requireProposal(proposalId); const job = this.requireJob(proposal.jobId); if (job.clientId !== clientId) throw new MarketplaceError('FORBIDDEN', 'Only the job owner can accept proposals'); if (this.acceptedJobs.has(job.id) || job.status !== 'open') throw new MarketplaceError('PROPOSAL_RACE_LOST', 'A proposal has already been accepted'); this.acceptedJobs.add(job.id); proposal.status = 'accepted'; job.status = 'contracted'; for (const other of this.proposals.values()) if (other.jobId === job.id && other.id !== proposal.id) other.status = 'rejected'; const contract: Contract = { id: randomUUID(), jobId: job.id, clientId, professionalId: proposal.professionalId, proposalId: proposal.id, status: 'active', milestones: [{ id: randomUUID(), title: 'Project delivery', amount: proposal.price, platformFee: Math.round(proposal.price * this.platformFeeRate * 100) / 100, status: 'draft' }] }; this.contracts.set(contract.id, contract); this.notify(proposal.professionalId, 'proposal.accepted', `Your proposal for ${job.title} was accepted.`); return contract; }
  async fundMilestone(clientId: string, contractId: string, milestoneId: string): Promise<void> { const { contract, milestone } = this.requireMilestone(contractId, milestoneId); if (contract.clientId !== clientId) throw new MarketplaceError('FORBIDDEN', 'Only client can fund'); if (milestone.status !== 'draft') throw new MarketplaceError('INVALID_MILESTONE_STATE', 'Milestone must be draft'); milestone.paymentIntentId = await this.payments.createHold(milestone.amount, contract.id, milestone.id); milestone.status = 'funded'; }
  async releaseMilestone(clientId: string, contractId: string, milestoneId: string): Promise<void> { const { contract, milestone } = this.requireMilestone(contractId, milestoneId); if (contract.clientId !== clientId) throw new MarketplaceError('FORBIDDEN', 'Only client can release'); if (milestone.status !== 'funded' || !milestone.paymentIntentId) throw new MarketplaceError('INVALID_MILESTONE_STATE', 'Milestone must be funded'); await this.payments.releaseHold(milestone.paymentIntentId, milestone.amount); milestone.status = 'released'; if (contract.milestones.every(m => m.status === 'released')) contract.status = 'completed'; this.notify(contract.professionalId, 'payment.released', 'A milestone payment was released.'); }
  openDispute(userId: string, contractId: string, milestoneId: string): void { const { contract, milestone } = this.requireMilestone(contractId, milestoneId); if (![contract.clientId, contract.professionalId].includes(userId)) throw new MarketplaceError('FORBIDDEN', 'Only contract parties can dispute'); if (milestone.status !== 'funded') throw new MarketplaceError('INVALID_MILESTONE_STATE', 'Only funded milestones can be disputed'); milestone.status = 'disputed'; contract.status = 'disputed'; }
  addReview(contractId: string, reviewerId: string, rating: number, comment: string): Review { const contract = this.requireContract(contractId); if (contract.status !== 'completed') throw new MarketplaceError('CONTRACT_NOT_COMPLETE', 'Reviews require completed contracts'); const revieweeId = reviewerId === contract.clientId ? contract.professionalId : contract.clientId; if (![contract.clientId, contract.professionalId].includes(reviewerId)) throw new MarketplaceError('FORBIDDEN', 'Only contract parties can review'); if (rating < 1 || rating > 5) throw new MarketplaceError('VALIDATION_ERROR', 'Rating must be between 1 and 5'); const review = { id: randomUUID(), contractId, reviewerId, revieweeId, rating, comment, flagged: false }; this.reviews.push(review); const profile = this.profiles.get(revieweeId); if (profile) { profile.rating = ((profile.rating * profile.reviewCount) + rating) / (profile.reviewCount + 1); profile.reviewCount += 1; } return review; }

  private notify(userId: string, topic: string, body: string): void { this.notifications.push({ id: randomUUID(), userId, topic, body, read: false, createdAt: new Date() }); }
  private requireUser(id: string): User { const user = this.users.get(id); if (!user) throw new MarketplaceError('NOT_FOUND', 'User not found'); return user; }
  private requireRole(id: string, role: Role): User { const user = this.requireUser(id); if (!user.roles.includes(role)) throw new MarketplaceError('FORBIDDEN', `Requires ${role} role`); return user; }
  private requireProfile(id: string): ProfessionalProfile { const profile = this.profiles.get(id); if (!profile) throw new MarketplaceError('PROFILE_REQUIRED', 'Professional profile required'); return profile; }
  private requireJob(id: string): JobPosting { const job = this.jobs.get(id); if (!job) throw new MarketplaceError('NOT_FOUND', 'Job not found'); return job; }
  private requireProposal(id: string): Proposal { const proposal = this.proposals.get(id); if (!proposal) throw new MarketplaceError('NOT_FOUND', 'Proposal not found'); return proposal; }
  private requireContract(id: string): Contract { const contract = this.contracts.get(id); if (!contract) throw new MarketplaceError('NOT_FOUND', 'Contract not found'); return contract; }
  private requireMilestone(contractId: string, milestoneId: string): { contract: Contract; milestone: Milestone } { const contract = this.requireContract(contractId); const milestone = contract.milestones.find(m => m.id === milestoneId); if (!milestone) throw new MarketplaceError('NOT_FOUND', 'Milestone not found'); return { contract, milestone }; }
}
